name: focus_widget_list
description: Focus Widget List allows user to focus on a paritcular widget of the list while blurring the other widgets in a list.
version: 0.0.1
homepage: https://github.com/Safal-Shrestha-SS/focus_widget_list

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  